### ISSUE TITLE
ImportError: cannot import name 'Literal'

### ISSUE THREAD

**Issue by CRT-HAO** [CWKevo/pyflarum#1]
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    from pyflarum import FlarumUser
  File "/usr/local/lib/python3.6/site-packages/pyflarum/__init__.py", line 1, in <module>
    from pyflarum.session import FlarumUser
  File "/usr/local/lib/python3.6/site-packages/pyflarum/session.py", line 1, in <module>
    from typing import Any, BinaryIO, Iterable, Optional, Literal, TYPE_CHECKING
ImportError: cannot import name 'Literal'
```

**Comment by CWKevo** [comment]
You're using Python 3.6, and it turny out that `Literal` was added in 3.8. I admit that I didn't know that it was added in such a recent version, and assumed that my package was 3.6+ compatible (https://www.python.org/dev/peps/pep-0586/)

I have tested my package against Python 3.9 only, but I'll look at making some backwards-compatible changes and release a new version, perhaps later today

**Comment by CWKevo** [comment]
I didn't test it, but I put `typing.Literal` in a string and used `typing as t` import instead. It works on Python 3.9.6, VSCode still picks the type hints, and it won't be used at runtime, since it's just a string. It should fix your issue, let me know if it worked, in case you will test it someday
